name: Generate flat index.md from /docs

on:
  push:
    branches: [main]

jobs:
  generate-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate index.md
        run: |
          SITE_URL="https://singularitysmith.github.io/AMTAIR_Prototype"
          INDEX_FILE="docs/index.md"

          echo "# 📂 Site Directory" > $INDEX_FILE
          echo "" >> $INDEX_FILE

          # Recursively find all files in /docs (excluding index.md itself)
          find docs -type f ! -name 'index.md' | while read filepath; do
            filename=$(basename "$filepath")
            echo "- [$filename]($SITE_URL/$filename)" >> $INDEX_FILE
          done

      - name: Commit and push if index.md changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/index.md
          git diff --cached --quiet || git commit -m "Update docs/index.md with directory listing"
          git push
