name: Auto-generate index.md for /docs

on:
  push:
    branches: [main]

jobs:
  generate-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate index.md
        run: |
          echo "# Directory Listing" > docs/index.md
          echo "" >> docs/index.md
          for file in docs/*; do
            filename=$(basename "$file")
            echo "- [$filename]($filename)" >> docs/index.md
          done

      - name: Commit and push index
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/index.md
          git commit -m "Auto-generate docs/index.md" || echo "No changes to commit"
          git push
